#pragma once

#include <typeinfo>
#include <fstream>
#include <filesystem>

constexpr unsigned short CELL_TYPE_TRIANGLE = 5;
constexpr unsigned short CELL_TYPE_RECTANGLE = 9;
constexpr short BC_TYPE = -1;

using namespace std;

template<typename T1,typename T2>
class vtkGenerator
{
    ofstream out;

public:

    vtkGenerator(const std::string& filename)
    {
        out.open(filename.c_str(),std::fstream::out);
    }

    void printInVTK(const FixedSizeMeshContainer<T1>& coords,const VariableSizeMeshContainer<T2>& topoEN)
    {
        out << "# vtk DataFile Version 2.0" << endl;
        out << "Generated by Maxkile's vtkGenerator" << endl;
        out << "ASCII" << endl;
        out << "DATASET UNSTRUCTURED_GRID" << endl;
        out << endl;
		size_t pointsNumber = coords.getBlockNumber();

        const char* type = "";
        if (!strcmp(typeid(T1).name(),"i"))
        {
            type = "int";
        }
        else if (!strcmp(typeid(T1).name(),"d"))
        {
            type = "float";
        }

        out << "POINTS " << pointsNumber << " " <<  type  << endl;

        coords.printContainer(out); 

        out << "CELLS " << topoEN.getBlockNumber() << " " << topoEN.getTotalSize() + topoEN.getBlockNumber() << endl;

        topoEN.printContainer(out);

        out << "CELL_TYPES " << topoEN.getBlockNumber() << endl;

        for (size_t i = 0; i < topoEN.getBlockNumber();++i)
        {
            switch(topoEN.getBlockSize(i))
            {
                case 3: out << CELL_TYPE_TRIANGLE << " ";
                        break;
                case 4: out << CELL_TYPE_RECTANGLE << " ";
                        break;
            }
        }

        out << endl;

        out << "POINT_DATA " << pointsNumber << endl;

        out << "SCALARS BCType " << type << " " << 1 << endl;

        out << "LOOKUP_TABLE " << "default" << endl;

        for (size_t i = 0; i < pointsNumber;++i)
        {
            out << BC_TYPE << " ";
        }

        out << endl;
    }

    ~vtkGenerator()
    {
        out.close();
    }
};
